# Site settings
title: Ninevillage
email: info@ninevillage.com
description: > # this means to ignore newlines until "baseurl:"
  Development for future. Ninevillage stands for innovation and efficiency.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ninevillage.com" # the base hostname & protocol for your site
twitter_username: Ninevillage
github_username:  Ninevillage

# Build settings
markdown: kramdown
